# Generated by Django 5.0.1 on 2024-02-03 15:08

import datetime
import django.db.models.deletion
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_author_blog_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('office_tel', models.CharField(max_length=20)),
                ('cellpone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AskForLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('back_time', models.DateTimeField(default=polls.models.AskForLeave.timeoffset)),
                ('place', models.CharField(max_length=200)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.person')),
            ],
        ),
    ]
